#!/bin/bash
echo "El Remitente"
read rem
$(cd ~/buzones/$rem 2> /dev/null)
if [ $? -gt 0 ] ; then
	echo "no existe $rem como remitente"
else
	echo "Destinatario"
	read des
	$(cd ~/buzones/$des 2> /dev/null) 
	if [ $? -gt 0 ] ; then
	echo "no existe $des como destinatario"
	else
		echo "Mensaje"
		read mm
		if (cat ~/buzones/$rem/out/$des 2> /dev/null) > 0 ; then
			echo -e "---------------\n $mm" >> ~/buzones/$rem/out/$des
			echo "Mensaje añadido en $des"
		else
			echo $mm > ~/buzones/$rem/out/$des
			echo "mensaje guardado"
		fi
	fi
fi
